##############NETWORKS##############
networks:
  default:
    name: media
    external: true
##############NETWORKS##############

services:
  bazarr: #subtitle grabber
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./bazarr:/config
      - $MEDIADIR:/media
    ports:
      - 6767:6767
    restart: unless-stopped
  
  

  overseerr: #media requesting tool
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./overseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  plex: # Media Server
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
      - DEBUG=no
      - PLEX_CLAIM=$PLEX_CLAIM
      - PLEX_PASS=$PLEX_PASS
      - ADVERTISE_IP=$PLEX_ADVERTISE_IP
    volumes:
      - ./plex:/config:rw
      - $PLEXMEDIA:/data/media:rw
      - /tmp:/transcode:rw
    devices:
      - /dev/dri:/dev/dri #required for Synology users
    network_mode: host

  prowlarr: #indexer manager for Sonarr & Radarr
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr: #movie search agent
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
      - DOCKER_MODS=gilbn/theme.park:sonarr 
      - TP_DOMAIN=gilbn.github.io 
      - TP_THEME=aquamarine
    volumes:
      - ./radarr:/config
      - $MEDIADIR:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: #TV show search agent
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
      - DOCKER_MODS=gilbn/theme.park:sonarr 
      - TP_DOMAIN=gilbn.github.io 
      - TP_THEME=aquamarine
    volumes:
      - ./sonarrV3:/config
      - $MEDIADIR:/media
    ports:
      - 8989:8989
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Etc/UTC
     - DELUGE_LOGLEVEL=error #optional
    volumes:
     - ./deluge:/config
     - $MEDIADIR/torrents:/media/torrents
    ports:
     - 8112:8112
     - 6881:6881
     - 6881:6881/udp
     - 58846:58846 #optional
    restart: unless-stopped

      #  qbittorrent:
      #image: lscr.io/linuxserver/qbittorrent:latest
      #container_name: qbittorrent
      #environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=Etc/UTC
      #- WEBUI_PORT=8080
      #volumes:
      #- ./qbittorrent:/config
      #- $MEDIADIR/torrents:/media/torrents
      #ports:
      #- 8080:8080
      #- 6881:6881
      #- 6881:6881/udp
      #restart: unless-stopped

  unmanic:
     container_name: unmanic
     image: josh5/unmanic:latest
     ports:
       - 8888:8888
     environment:
       - PUID=$PUID
       - PGID=$PGID
     volumes:
       - ./unmanic:/config
       - $PLEXMEDIA:/library
       - /tmp/unmanic:/tmp/unmanic
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /.jacket:/config
    ports:
      - 9117:9117
    restart: unless-stopped
